# Generated by Django 5.0.6 on 2024-07-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attsystem", "0002_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
