# Generated by Django 5.0.6 on 2024-07-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attsystem", "0003_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
