# Generated by Django 5.0.6 on 2024-07-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attsystem", "0004_alter_customuser_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="holiday_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("occasion", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
