# Generated by Django 5.0.6 on 2024-07-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attsystem", "0005_holiday_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_respond",
            field=models.BooleanField(default=False),
        ),
    ]
